version: '3.1'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
      # - "5432:5432"
    restart: always

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command: /bin/sh -c "sleep 10 && go/bin/goose -dir /migrations postgres \"${PG_URL}\" up"
    depends_on:
      - postgres

  go-unimates:
    build:
      context: .
    container_name: bot_service
    env_file:
      - .env
    volumes:
      - ./config:/config
    ports:
      - "8080:8080"
    command: /bin/sh -c "sleep 15 && ./unimates --config=/config/config.yaml"
    restart: always
    depends_on:
      - postgres