FROM golang:alpine AS builder
WORKDIR /migrate
COPY ./migrations .
RUN go mod init migrate
RUN go install -tags 'postgres' github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest
WORKDIR /migrate
COPY --from=builder go/bin/goose go/bin/goose
COPY ./migrations .